title: "Pinkingrey"
description: "Nothing to do, but just do it."
author:
  name: "ns7137"
  email: "sunqiwei@gmail.com"
  url: "ns7137.github.io"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  
owner: ns7137
year: 2021