title: ns7137 Blog
iconURL: assets/default-icon.png
theme: green

# for a clean URL
permalink: :slug

social:
  github: ns7137

plugins:
 - jekyll-feed
 - jekyll-seo-tag

### comments & analytics
hyvor_talk_website_id: 14
google_analytics: UA-NNNNNNNN-N